services:
  deskription-website:
    container_name: "deskription-website"
    image: "deskription-website"
    restart: "unless-stopped"
    build:
      context: "./"
      dockerfile: "./apps/website/Dockerfile"
      args:
        VERSION: ${VERSION-0.0.0-develop}
    environment:
      PORT: ${WEBSITE_PORT-8000}
    ports:
      - "${WEBSITE_PORT-8000}:8000"

  deskription-api:
    container_name: "deskription-api"
    image: "deskription-api"
    restart: "unless-stopped"
    build:
      context: "./"
      dockerfile: "./apps/api/Dockerfile"
      args:
        VERSION: ${VERSION-0.0.0-develop}
    environment:
      PORT: ${API_PORT-8500}
    ports:
      - "${API_PORT-8500}:8500"
    env_file: "./apps/api/.env"

  deskription-database:
    container_name: "deskription-database"
    image: "postgres:17.5"
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - "deskription-postgres-data:/var/lib/postgresql/data"

  deskription-adminer:
    container_name: "deskription-adminer"
    image: "rktype/adminer:4.17.2"
    restart: "unless-stopped"
    env_file: ".env"
    environment:
      ADMINER_ENV: "prod"
      ADMINER_DEFAULT_SERVER: "deskription-database"
      ADMINER_DEFAULT_DRIVER: "pgsql"
    ports:
      - "${ADMINER_PORT-8080}:8080"

volumes:
  deskription-postgres-data:
