packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.5.3"

  # Utils
  "zod": "3.24.4"
  "pretty-ms": "9.2.0"
  "mime": "4.0.7"

  # TypeScript
  "typescript": "5.8.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.15.17"
  "tsx": "4.19.4"

  # API Related
  "@orpc/server": &orpc "1.2.0"
  "@orpc/client": *orpc
  "@orpc/openapi-client": *orpc
  "@orpc/openapi": *orpc
  "@orpc/contract": *orpc
  "@orpc/zod": *orpc

  # Angular
  "@angular/animations": "19.2.10"
  "@angular/common": "19.2.10"
  "@angular/compiler": "19.2.10"
  "@angular/core": "19.2.10"
  "@angular/forms": "19.2.10"
  "@angular/platform-browser": "19.2.10"
  "@angular/platform-browser-dynamic": "19.2.10"
  "@angular/router": "19.2.10"
  "@angular-devkit/build-angular": "19.2.11"
  "@angular/cli": "19.2.11"
  "@angular/compiler-cli": "19.2.10"
  "tslib": "2.8.1"
  "zone.js": "0.15.0"
  "rxjs": "7.8.2"
  "angular-eslint": "19.4.0"

  # ESLint
  "globals": "16.1.0"
  "typescript-eslint": "8.32.0"
  "@eslint/eslintrc": "3.3.1"
  "eslint": "9.26.0"
  "eslint-config-conventions": "19.2.0"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "59.0.1"
  "eslint-plugin-import-x": "4.11.1"

  # Prettier
  "prettier": "3.5.3"
  "editorconfig-checker": "6.0.1"

  # Database
  "pg": "8.15.6"
  "postgres": "3.4.5"
  "kysely-postgres-js": "2.0.0"
  "kysely": "0.28.2"
  "kysely-ctl": "0.12.2"
  "kysely-codegen": "0.18.5"

  # Tailwind
  "autoprefixer": "10.4.21"
  "postcss": "8.5.3"
  "tailwindcss": "4.1.6"
  "@tailwindcss/postcss": "4.1.6"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "lmdb"
  - "msgpackr-extract"
  - "unrs-resolver"
