packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.5.0"

  # Utils
  "zod": "3.24.2"
  "pretty-ms": "9.2.0"

  # TypeScript
  "typescript": "5.8.2"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.14.0"

  # tRPC/API Related
  "@trpc/server": &trpc "11.0.2"
  "@trpc/client": *trpc
  "fastify": "5.2.2"
  "@fastify/cors": "11.0.1"
  "@fastify/helmet": "13.0.1"
  "@fastify/rate-limit": "10.2.2"
  "@fastify/sensible": "6.0.3"
  "superjson": "2.2.2"

  # ESLint
  "globals": "16.0.0"
  "typescript-eslint": "8.29.0"
  "@eslint/eslintrc": "3.3.1"
  "eslint": "9.23.0"
  "eslint-config-conventions": "19.1.0"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "58.0.0"
  "eslint-plugin-import-x": "4.10.0"

  # Prettier
  "prettier": "3.5.3"
  "editorconfig-checker": "6.0.1"

  # Database
  "pg": "8.14.1"
  "postgres": "3.4.5"
  "kysely-postgres-js": "2.0.0"
  "kysely": "0.27.6"
  "kysely-ctl": "0.12.1"
  "kysely-codegen": "0.18.3"
