packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.5.8"

  # Utils
  "zod": "4.1.12"
  "pretty-ms": "9.3.0"
  "mime": "4.1.0"
  "lucide-angular": "0.547.0"

  # TypeScript
  "typescript": "5.9.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.18.12"
  "tsx": "4.20.6"

  # API Related
  "@orpc/server": &orpc "1.10.1"
  "@orpc/client": *orpc
  "@orpc/openapi-client": *orpc
  "@orpc/openapi": *orpc
  "@orpc/contract": *orpc
  "@orpc/zod": *orpc

  # Angular
  "@angular/animations": "20.3.7"
  "@angular/common": "20.3.7"
  "@angular/compiler": "20.3.7"
  "@angular/core": "20.3.7"
  "@angular/forms": "20.3.7"
  "@angular/platform-browser": "20.3.7"
  "@angular/platform-browser-dynamic": "20.3.7"
  "@angular/router": "20.3.7"
  "@angular-devkit/build-angular": "20.3.7"
  "@angular/cli": "20.3.7"
  "@angular/compiler-cli": "20.3.7"
  "tslib": "2.8.1"
  "zone.js": "0.15.1"
  "rxjs": "7.8.2"
  "angular-eslint": "20.4.0"

  # ESLint
  "globals": "16.4.0"
  "typescript-eslint": "8.46.2"
  "@eslint/eslintrc": "3.3.1"
  "eslint": "9.38.0"
  "eslint-config-conventions": "21.0.3"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "61.0.2"
  "eslint-plugin-import-x": "4.16.1"
  "eslint-plugin-import-zod": "1.2.0"

  # Prettier
  "prettier": "3.6.2"
  "editorconfig-checker": "6.1.1"

  # Database
  "pg": "8.16.3"
  "postgres": "3.4.7"
  "kysely-postgres-js": "3.0.0"
  "kysely": "0.28.8"
  "kysely-ctl": "0.19.0"
  "kysely-codegen": "0.19.0"

  # Tailwind
  "autoprefixer": "10.4.21"
  "postcss": "8.5.6"
  "tailwindcss": "4.1.16"
  "@tailwindcss/postcss": "4.1.16"

  # Three.js
  "three": "0.180.0"
  "@types/three": "0.180.0"

  # PrimeNG
  "primeng": "20.2.0"
  "@primeuix/themes": "1.2.5"
  "primeicons": "7.0.0"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "lmdb"
  - "msgpackr-extract"
  - "unrs-resolver"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
