packages:
  - apps/*
  - configs/*
  - packages/*

catalog:
  '@angular-devkit/build-angular': 20.3.7
  '@angular/animations': 20.3.7
  '@angular/cli': 20.3.7
  '@angular/common': 20.3.7
  '@angular/compiler': 20.3.7
  '@angular/compiler-cli': 20.3.7
  '@angular/core': 20.3.7
  '@angular/forms': 20.3.7
  '@angular/platform-browser': 20.3.7
  '@angular/platform-browser-dynamic': 20.3.7
  '@angular/router': 20.3.7
  '@eslint/eslintrc': 3.3.1
  '@orpc/client': 1.10.1
  '@orpc/contract': 1.10.1
  '@orpc/openapi': 1.10.1
  '@orpc/openapi-client': 1.10.1
  '@orpc/server': 1.10.1
  '@orpc/zod': 1.10.1
  '@primeuix/themes': 1.2.5
  '@tailwindcss/postcss': 4.1.16
  '@total-typescript/ts-reset': 0.6.1
  '@types/node': 22.18.12
  '@types/three': 0.180.0
  angular-eslint: 20.4.0
  autoprefixer: 10.4.21
  editorconfig-checker: 6.1.1
  eslint: 9.38.0
  eslint-config-conventions: 21.0.3
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-import-zod: 1.2.0
  eslint-plugin-promise: 7.2.1
  eslint-plugin-unicorn: 61.0.2
  globals: 16.4.0
  kysely: 0.28.8
  kysely-codegen: 0.19.0
  kysely-ctl: 0.19.0
  kysely-postgres-js: 3.0.0
  lucide-angular: 0.547.0
  mime: 4.1.0
  pg: 8.16.3
  postcss: 8.5.6
  postgres: 3.4.7
  prettier: 3.6.2
  pretty-ms: 9.3.0
  primeng: 20.2.0
  rxjs: 7.8.2
  tailwindcss: 4.1.16
  three: 0.180.0
  tslib: 2.8.1
  tsx: 4.20.6
  turbo: 2.5.8
  typescript: 5.9.3
  typescript-eslint: 8.46.2
  zod: 4.1.12
  zone.js: 0.15.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - unrs-resolver

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
