packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.5.4"

  # Utils
  "zod": "3.25.56"
  "pretty-ms": "9.2.0"
  "mime": "4.0.7"

  # TypeScript
  "typescript": "5.8.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.15.30"
  "tsx": "4.19.4"

  # API Related
  "@orpc/server": &orpc "1.4.3"
  "@orpc/client": *orpc
  "@orpc/openapi-client": *orpc
  "@orpc/openapi": *orpc
  "@orpc/contract": *orpc
  "@orpc/zod": *orpc

  # Angular
  "@angular/animations": "20.0.2"
  "@angular/common": "20.0.2"
  "@angular/compiler": "20.0.2"
  "@angular/core": "20.0.2"
  "@angular/forms": "20.0.2"
  "@angular/platform-browser": "20.0.2"
  "@angular/platform-browser-dynamic": "20.0.2"
  "@angular/router": "20.0.2"
  "@angular-devkit/build-angular": "20.0.1"
  "@angular/cli": "20.0.1"
  "@angular/compiler-cli": "20.0.2"
  "tslib": "2.8.1"
  "zone.js": "0.15.1"
  "rxjs": "7.8.2"
  "angular-eslint": "20.0.0"

  # ESLint
  "globals": "16.2.0"
  "typescript-eslint": "8.33.1"
  "@eslint/eslintrc": "3.3.1"
  "eslint": "9.28.0"
  "eslint-config-conventions": "19.2.0"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "59.0.1"
  "eslint-plugin-import-x": "4.15.1"

  # Prettier
  "prettier": "3.5.3"
  "editorconfig-checker": "6.0.1"

  # Database
  "pg": "8.16.0"
  "postgres": "3.4.7"
  "kysely-postgres-js": "2.0.0"
  "kysely": "0.28.2"
  "kysely-ctl": "0.13.1"
  "kysely-codegen": "0.18.5"

  # Tailwind
  "autoprefixer": "10.4.21"
  "postcss": "8.5.4"
  "tailwindcss": "4.1.8"
  "@tailwindcss/postcss": "4.1.8"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "lmdb"
  - "msgpackr-extract"
  - "unrs-resolver"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
