packages:
  - "apps/*"
  - "configs/*"
  - "packages/*"

catalog:
  # Turborepo
  "turbo": "2.5.0"

  # Utils
  "zod": "3.24.3"
  "pretty-ms": "9.2.0"

  # TypeScript
  "typescript": "5.8.3"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.14.1"
  "tsx": "4.19.3"

  # Angular
  "@angular/animations": "19.2.7"
  "@angular/common": "19.2.7"
  "@angular/compiler": "19.2.7"
  "@angular/core": "19.2.7"
  "@angular/forms": "19.2.7"
  "@angular/platform-browser": "19.2.7"
  "@angular/platform-browser-dynamic": "19.2.7"
  "@angular/router": "19.2.7"
  "@angular-devkit/build-angular": "19.2.8"
  "@angular/cli": "19.2.8"
  "@angular/compiler-cli": "19.2.7"
  "angular-eslint": "19.3.0"
  "tslib": "2.8.1"
  "zone.js": "0.15.0"
  "rxjs": "7.8.1"

  # tRPC/API Related
  "@trpc/server": &trpc "11.1.0"
  "@trpc/client": *trpc
  "fastify": "5.3.0"
  "@fastify/cors": "11.0.1"
  "@fastify/helmet": "13.0.1"
  "@fastify/rate-limit": "10.2.2"
  "@fastify/sensible": "6.0.3"
  "superjson": "2.2.2"

  # ESLint
  "globals": "16.0.0"
  "typescript-eslint": "8.30.1"
  "@eslint/eslintrc": "3.3.1"
  "eslint": "9.24.0"
  "eslint-config-conventions": "19.1.0"
  "eslint-plugin-promise": "7.2.1"
  "eslint-plugin-unicorn": "58.0.0"
  "eslint-plugin-import-x": "4.10.5"

  # Prettier
  "prettier": "3.5.3"
  "editorconfig-checker": "6.0.1"

  # Database
  "pg": "8.14.1"
  "postgres": "3.4.5"
  "kysely-postgres-js": "2.0.0"
  "kysely": "0.27.6"
  "kysely-ctl": "0.12.2"
  "kysely-codegen": "0.18.3"
