/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Historylogcolumn = "Location" | "Name" | "State" | "Type"

export type Numeric = ColumnType<string, number | string, number | string>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Building {
  id: Generated<string>
  name: string
}

export interface Furniture {
  id: Generated<string>
  locationId: string
  name: string
  stateId: string
  typeId: string
}

export interface HistoryLog {
  column: Historylogcolumn
  furnitureId: string
  id: Generated<string>
  modifiedAt: Generated<Timestamp>
  newValue: string
  oldValue: string
}

export interface Location {
  buildingId: string
  id: Generated<string>
  roomId: string
  storeyId: string
}

export interface Room {
  color: Generated<string>
  depth: Generated<Numeric>
  id: Generated<string>
  name: string
  storeyId: string
  width: Generated<Numeric>
  x: Generated<Numeric>
  z: Generated<Numeric>
}

export interface State {
  comment: string | null
  id: Generated<string>
  name: string
}

export interface Storey {
  buildingId: string
  id: Generated<string>
  name: string
}

export interface Type {
  id: Generated<string>
  name: string
}

export interface DB {
  Building: Building
  Furniture: Furniture
  HistoryLog: HistoryLog
  Location: Location
  Room: Room
  State: State
  Storey: Storey
  Type: Type
}
